version: 2.1
orbs:
#orb versions used are according to the versions listed on https://circleci.com/developer/orbs/ 
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.4.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
#browser-tools orb is installed to run the frontend tests
  browser-tools: circleci/browser-tools@1.2.5

jobs:
    build:
      docker:
        - image: "cimg/base:stable"
      steps:
        - node/install
        - checkout
        - aws-cli/setup
        - eb/setup
        - browser-tools/install-browser-tools

        - run:
            name: "Frontend Install"
            command: |
              npm run frontend:install
        - run:
            name: "Backend Install"
            command: |
              npm run backend:install
        - run:
            name: "Frontend Build"
            command: |
              npm run frontend:build
        - run:
            name: "Backend Build"
            command: |
              npm run backend:build
        - run:
            name: "Backend Deploy"
            command: |
              npm run backend:deploy
        - run:
            name: "Frontend Deploy"
            command: |
              npm run frontend:deploy
        - run:
            name: "Backend Test"
            command: |
              npm run backend:test              
        - run:
            name: "Frontend Test"
            command: |
              npm run frontend:test


workflows:
  build-and-deploy-workflow:
    jobs:
      - build